### PR TITLE
requests, paths, etc

### PR DESCRIPTION
**Pull request by davidlehn**
Looking for feedback on the doc loader API:
-  Should it more closely match the jsonld.js one?  (ie, a documentLoader.requests object or similar)
-  This one doesn't have to support web and servers but it's still a similar pattern that allows using custom loaders.  There might be a use case for changing things to support the old API vs requests lib.
- Is it worth the trouble to made 'requests' optional and provide a simpler (though maybe broken) loader like the old code?

The path futzing changes pass the tests now but it's unclear how correct or optimal it is.  I just moved closer to what jsonld.js does.

### CODE REVIEW

**Comment by davidlehn** [comment]
Addresses:
- https://github.com/digitalbazaar/pyld/issues/57
- https://github.com/digitalbazaar/pyld/issues/65

**Comment by Elizafox** [comment]
requests is quite a common dependency so I see no harm in depending on it.

**Comment by jkreft-usgs** [comment]
It would be pretty sweet if this PR could be merged and released soon.  I have several projects that could take advantage of pyld it right away.

**Comment by davidlehn** [comment]
Ok, I'll merge and release. Please file issues for bugs or suggestions. We have been using jsonld.js much more than this lib lately so do appreciate feedback for things we may miss beyond what's in the test suite.

**Pull request merged**
